CASM-3727: Write out product catalog data
Write out product catalog data to the output file specified by
${SCRIPT_OUTPUT_FILE}.
Made some other minor tweaks defining variables once rather than
running basename repeatedly.

diff --git a/bin/loftsman-manifest-upload b/bin/loftsman-manifest-upload
--- a/bin/loftsman-manifest-upload
+++ b/bin/loftsman-manifest-upload
@@ -2,7 +2,7 @@
 #
 # MIT License
 #
-# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
+# (C) Copyright 2022-2023 Hewlett Packard Enterprise Development LP
 #
 # Permission is hereby granted, free of charge, to any person obtaining a
 # copy of this software and associated documentation files (the "Software"),
@@ -66,6 +66,8 @@ process(){
         return 1
     fi
 
+    CATALOG_UPDATE='{"component_version": {"manifests": []}}'
+
     # Is $manifest_path a directory?
     if [[ -d "$manifest_path" ]]; then
         manifest_files=$(ls "$manifest_path"/*.yml "$manifest_path"/*.yaml 2>/dev/null)
@@ -80,11 +82,15 @@ process(){
                 fi
                 rm -f $name
             fi
-            if ! cray artifacts create config-data argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/"$(basename $manifest)" $manifest; then
-                echo "ERROR failed to create s3://config-data/argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/$(basename $manifest)"
+            manifest_name="$(basename $manifest)"
+            s3_manifest_key="argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/$manifest_name"
+            s3_manifest_path="config-data/$s3_anifest_key"
+            if ! cray artifacts create config-data $s3_manifest_key $manifest; then
+                echo "ERROR failed to create s3://$s3_manifest_path"
                 exit 1
             else
-                echo "NOTICE successfully created s3://config-data/argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/$(basename $manifest)"
+                echo "NOTICE successfully created s3://$s3_manifest_path"
+                CATALOG_UPDATE=$(echo "$CATALOG_UPDATE" | jq ".component_version.manifests += [\"$s3_manifest_path\"]");
             fi
         done
     # or is it a file?
@@ -99,17 +105,28 @@ process(){
             fi
             rm -f $name
         fi
-        if ! cray artifacts create config-data argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/"$(basename $manifest_path)" "$manifest_path"; then
-            echo "ERROR Error uploading to S3"
+        manifest_name="$(basename $manifest_path)"
+        s3_manifest_key="argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/$manifest_name"
+        s3_manifest_path="config-data/$s3_manifest_key"
+        if ! cray artifacts create config-data $s3_manifest_key $manifest_path; then
+            echo "ERROR Error uploading $manifest_name to S3"
             return 1
         else
-            echo "NOTICE successfully created s3://config-data/argo/loftsman/$PRODUCT_NAME/$PRODUCT_VERSION/manifests/$(basename $manifest_path)"
-            return 0
+            echo "NOTICE successfully created s3://$s3_manifest_path"
+            CATALOG_UPDATE=$(echo "$CATALOG_UPDATE" | jq ".component_version.manifests += [\"$s3_manifest_path\"]");
         fi
     else
         echo "ERROR $0: Invalid path \"$manifest_path\""
         echo "ERROR Skipping the loftsman manifest upload operation for $manifest_path"
         return 1
+    fi
+
+    # Write the output file
+    if [[ -n "$SCRIPT_OUTPUT_FILE" ]]; then
+        echo "NOTICE Writing product catalog data to output file: $SCRIPT_OUTPUT_FILE"
+        echo "$CATALOG_UPDATE" > $SCRIPT_OUTPUT_FILE
+    else
+        echo "WARNING SCRIPT_OUTPUT_FILE environment variable was null."
     fi
 }
 
